references:
  build_config: &build_config
    machine: true
    environment:
      - DOCKER_FILE: ./Dockerfile

version: 2
jobs:
  test:
    <<: *build_config
    steps:
      - checkout
      - run: cp Gemfile.lock Gemfile.lock.cache_key

      - run: bundle install --path vendor/bundle
  deploy:
    <<: *build_config
    steps:
      - checkout
      - attach_workspace:
          at: ~/app/linode_test
      - add_ssh_keys:
          fingerprints:
            - "1a:35:73:5c:4a:e8:fa:e2:5b:9c:42:f3:4a:0c:e5:49"
      - checkout
      - run: cp Gemfile.lock Gemfile.lock.cache_key
      - run:
          command: |
              ssh root@139.162.21.191 "bash -x ~/app/deployment.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy
      # - test
